# APS 3 - Aula 20
---

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from funcoesTermosol import *
from app_utils import *

In [2]:
num_nos, matriz_nos, num_membros, matriz_incidencia, num_cargas, v_carregamento, num_rest, v_rest = importa("entrada_aps3.xlsx")

In [3]:
v_rest

array([[0.],
       [1.],
       [3.],
       [5.],
       [7.],
       [8.],
       [9.]])

In [4]:
matriz_incidencia

array([[1.00000000e+00, 2.00000000e+00, 2.10000000e+11, 7.06858347e-02],
       [2.00000000e+00, 3.00000000e+00, 2.10000000e+11, 7.06858347e-02],
       [3.00000000e+00, 4.00000000e+00, 2.10000000e+11, 7.06858347e-02],
       [4.00000000e+00, 5.00000000e+00, 2.10000000e+11, 7.06858347e-02],
       [1.00000000e+00, 6.00000000e+00, 2.10000000e+11, 7.06858347e-02],
       [2.00000000e+00, 6.00000000e+00, 2.10000000e+11, 7.06858347e-02],
       [2.00000000e+00, 7.00000000e+00, 2.10000000e+11, 7.06858347e-02],
       [6.00000000e+00, 7.00000000e+00, 2.10000000e+11, 7.06858347e-02],
       [3.00000000e+00, 7.00000000e+00, 2.10000000e+11, 7.06858347e-02],
       [4.00000000e+00, 7.00000000e+00, 2.10000000e+11, 7.06858347e-02],
       [7.00000000e+00, 8.00000000e+00, 2.10000000e+11, 7.06858347e-02],
       [4.00000000e+00, 8.00000000e+00, 2.10000000e+11, 7.06858347e-02],
       [5.00000000e+00, 8.00000000e+00, 2.10000000e+11, 7.06858347e-02],
       [6.00000000e+00, 9.00000000e+00, 2.10000000e

In [5]:
conectividade_global = conec_global_T(matriz_incidencia, num_membros, num_nos)

In [6]:
matriz_dos_membros = np.dot(matriz_nos, conectividade_global)

In [7]:
KG = matriz_global(num_nos, num_membros, matriz_incidencia, matriz_nos, matriz_dos_membros)

In [8]:
Pg = vetor_global_de_forcas(num_rest, v_rest, v_carregamento) # Condição de contorno

In [9]:
KG_solucao = MR_para_solucao(KG, v_rest)

In [10]:
u = calcula_deslocamentos(KG_solucao, Pg)

In [11]:
# Para nossa APS descobrimos u3, u5, u7, u11, u12, u13, u14, u15, u16, u17, u18,
u

array([[ 7.17776427e-08],
       [ 2.07213119e-07],
       [ 3.42648596e-07],
       [ 8.47655338e-07],
       [-4.84582362e-07],
       [ 7.93300326e-07],
       [-9.01574228e-07],
       [ 1.15337155e-06],
       [-3.60071227e-07],
       [ 1.70043042e-06],
       [-2.34489036e-06]])

In [12]:
def completa_u(matriz_u, vet_rest):
    #faz a matriz virar lista
    lista=[]
    for e in matriz_u[:,0]:
        lista.append(e)
    
    
    ## Inserir zeros no u que não tem para assim complentar
    
    for i in vet_rest[:,0]:
        lista.insert(int(i), 0)
        
    # Transforma em vetor de novo
    matriz=np.array([lista])
    matriz=matriz.T
    
    return matriz
    
    

In [13]:
u_completo = completa_u(u, v_rest)

print(u_completo)
print(u_completo.shape)

[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 7.17776427e-08]
 [ 0.00000000e+00]
 [ 2.07213119e-07]
 [ 0.00000000e+00]
 [ 3.42648596e-07]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 8.47655338e-07]
 [-4.84582362e-07]
 [ 7.93300326e-07]
 [-9.01574228e-07]
 [ 1.15337155e-06]
 [-3.60071227e-07]
 [ 1.70043042e-06]
 [-2.34489036e-06]]
(18, 1)


Temos que descobrir R1x, R1y, R2y, R3y, R4y, R5x, R5y

In [14]:
R1x = calculate_force(KG, u_completo, 0)
print(R1x)

[-1485.46628629]


In [15]:
def calculate_force_complete(KG, u_completo, vet_rest):
    lista_forcas = []
    for i in vet_rest[:,0]:
        lista_forcas.append(calculate_force(KG, u_completo, int(i)))
        
    return lista_forcas
        

In [16]:
forcas = calculate_force_complete(KG, u_completo, v_rest)
print(len(forcas))

7


In [17]:
i=0
while(i<len(forcas)):
    if i==0:
        print("R1x:"+str(forcas[i]))
    elif i==1:
        print("R1y:"+str(forcas[i]))
    elif i==2:
        print("R2y:"+str(forcas[i]))
    elif i==3:
        print("R3y:"+str(forcas[i]))
    elif i==4:
        print("R4y:"+str(forcas[i]))
    elif i==5:
        print("R5x:"+str(forcas[i]))
    elif i==6:
        print("R5y:"+str(forcas[i]))
    
    i=i+1  
        
    

R1x:[-1485.46628629]
R1y:[-952.73171494]
R2y:[4069.04566302]
R3y:[6691.49532106]
R4y:[6220.79922859]
R5x:[-6514.53371371]
R5y:[3971.39150227]


In [19]:
for i in range(num_membros):
    tensao, deformacao, forca = tensao_e_deformacao(i+1, num_membros, u_completo, matriz_incidencia, matriz_nos, matriz_incidencia[0,2])
    print("Membro {0}: tensao: {1} | deformacao: {2} | força: {3}".format(i+1, tensao, deformacao, forca))

Membro 1: tensao: 7536.652478778937 | deformacao: 3.5888821327518746e-08 | força: 1582697020543576.8
Membro 2: tensao: 14220.725046637504 | deformacao: 6.771773831732145e-08 | força: 2986352259793876.0
Membro 3: tensao: 14220.725046637503 | deformacao: 6.771773831732144e-08 | força: 2986352259793875.5
Membro 4: tensao: -35978.10257205395 | deformacao: -1.7132429796216164e-07 | força: -7555401540131329.0
Membro 5: tensao: 19061.33128625371 | deformacao: 9.076824422025577e-08 | força: 4002879570113279.0
Membro 6: tensao: -50881.147959795846 | deformacao: -2.422911807609326e-07 | força: -1.0685041071557128e+16
Membro 7: tensao: -9452.706077351546 | deformacao: -4.501288608262641e-08 | força: -1985068276243824.8
Membro 8: tensao: -5707.276250655817 | deformacao: -2.7177505955503892e-08 | força: -1198528012637721.8
Membro 9: tensao: -94665.2939575716 | deformacao: -4.507871140836743e-07 | força: -1.9879711731090036e+16
Membro 10: tensao: -70991.86283358253 | deformacao: -3.380564896837264e-

In [20]:
tensao, deformacao, forca = tensao_e_deformacao(1, num_membros, u_completo, matriz_incidencia, matriz_nos, matriz_incidencia[0,2])

In [21]:
calcula_deslocamentos(KG_solucao, Pg)

array([[ 7.17776427e-08],
       [ 2.07213119e-07],
       [ 3.42648596e-07],
       [ 8.47655338e-07],
       [-4.84582362e-07],
       [ 7.93300326e-07],
       [-9.01574228e-07],
       [ 1.15337155e-06],
       [-3.60071227e-07],
       [ 1.70043042e-06],
       [-2.34489036e-06]])

In [22]:
solucao_gauss(KG_solucao, Pg, 100, 1e-3)

  0%|                                                                                          | 0/100 [00:00<?, ?it/s]C:\Users\Lais Nascimento\Desktop\5-semestre\Transferência de Calor e Mecânica dos Sólidos\mecsol-APS3\app_utils.py:207: RuntimeWarning: invalid value encountered in double_scalars
  return max( abs( (s2 - s1)/s2) for s1,s2 in zip(array1, array2))
  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

Convergiu na 26º iteracao


array([[ 7.16003472e-08],
       [ 2.07027928e-07],
       [ 3.42505492e-07],
       [ 8.47262671e-07],
       [-4.84504699e-07],
       [ 7.92965963e-07],
       [-9.01590777e-07],
       [ 1.15307568e-06],
       [-3.60122344e-07],
       [ 1.70015054e-06],
       [-2.34491461e-06]])

In [23]:
solucao_jacobi(KG_solucao, Pg, 100, 1e-3)

array([[ 7.17776427e-08],
       [ 2.07213119e-07],
       [ 3.42648596e-07],
       [ 8.47655338e-07],
       [-4.84582362e-07],
       [ 7.93300326e-07],
       [-9.01574228e-07],
       [ 1.15337155e-06],
       [-3.60071227e-07],
       [ 1.70043042e-06],
       [-2.34489036e-06]])